### ISSUE TITLE
Template to add a bug in the backlog

### ISSUE THREAD

**Issue by morgadoCV** [SoftCactusTeam/Warcraft_Adventures#1]
Build:

Type:

Severity:
[ ]Critical
[ ]Major
[ ]Minor

Priority:
[ ]Urgent
[ ]High
[ ]Normal
[ ]Low

Steps to reproduce:

Frequency:

**Comment by Jony635** [comment]
I've included a file in the repository in order to the template appears when you add a new issue. 
We can close this one now.
